### ISSUE TITLE
Prefab ID Not Updating VNEI v.0.9.0 - visual bug?

### ISSUE THREAD

**Issue by ValhallaCommunity** [MSchmoecker/VNEI#14] opened 2023-03-15 20:21 UTC
Hey MSchmoecker!

There might be a tiny UI update needed. Sometimes when I click an item, it shows the prior items prefab ID. Notice Small Bucket is staying no matter what item I click.

![image](https://user-images.githubusercontent.com/124803112/225432225-5d94f550-bb87-4166-bcf5-c45e706b1a3c.png)
![image](https://user-images.githubusercontent.com/124803112/225432275-dee02786-eb23-438a-9539-f9d5f8eb77d2.png)

It could be an issue with Clutter mod objects when clicking them. The issue resolves itself when relogging.

Thank you for taking a peak!

**Comment by MSchmoecker** [comment] 2023-03-15 20:59
Hi, can you please send your log file from 'BepInEx/LogOutput.log' after this occurred? After the Valheim update a lot of UI mods (VNEI included) had issues duo to changed method signatures and I want to first make sure no other errors are causing this.

**Comment by MSchmoecker** [comment] 2023-03-15 21:22
I've debugged this now and the problem is duo to how vanilla code interacts with the prefab name of Clutter. Clutter uses a localized token as the prefab name which is cached by the localization system while normal prefab names are not localized and not cached. This causes the wrong text to display. Will be fixed in the next update.

**Comment by ValhallaCommunity** [comment] 2023-03-16 04:59
Thanks MSchmoecker! I would have provided log, I got pulled away for the new born! I can test if needed!

**Comment by MSchmoecker** [comment] 2023-03-16 20:07
Fixed in 0.9.1

**Closed by MSchmoecker** 2023-03-16 20:07 UTC
